<?php

/**
 * @file
 * Contains training_drupal_8.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\menu_link_content\Entity\MenuLinkContent;

/**
 * Implements hook_help().
 */
function training_drupal_8_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the training_drupal_8 module.
    case 'help.page.training_drupal_8':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Training Drupal 8') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_install().
 */
function training_drupal_8_install() {
  $menu_link = MenuLinkContent::create([
    'title' => 'Trainig D8 - Hello',
    'link' => ['uri' => 'internal:/training-drupal-8/hello'],
    'menu_name' => 'main',
    'weight' => 2,
    'expanded' => TRUE,
  ]);

  $menu_link->save();
}
