<?php

/**
 * @file
 * Contains training_drupal_8.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function training_drupal_8_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the training_drupal_8 module.
    case 'help.page.training_drupal_8':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Training Drupal 8') . '</p>';
      return $output;

    default:
  }
}
